export * from './department-type';
export * from './faculty-type';
export * from './lecturer-type';
export * from './organization-login-response.type';
export * from './password-reset-response.type';
export * from './register-response.type';
export * from './reset-response.type';
export * from './student-login-response.type';
export * from './validation-response.type';
